Repository WhileNotSuccess/practice_community_react, pull requests merged in 2024-11, with the labels that each got.

#54 🎨 style : login, sign-in 페이지 css 수정
  src/css/LoginComp.css
  src/css/SignInComp.css
  src/pages/Login.js
Labels: bug

#58 Feature/list
  src/App.js
  src/css/LoginComp.css
  src/css/SignInComp.css
  src/pages/ListIn.jsx
  src/pages/Login.js
  src/pages/SignIn.js
Labels: bug, enhancement

#67 이메일 인증 및 비밀번호 찾기 구현
  src/App.js
  src/hooks/auth.js
  src/pages/EmailVerify.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Login.js
  src/pages/PasswordReset.jsx
  src/pages/UserTest.js
Labels: enhancement

#66 postList.js의 마우스 우클릭함수 추가 및 post.js, postUpdate.js alert구문 추가, 마우스 커서 변경
  src/components/PostList.js
  src/css/MainComp.css
  src/css/PostComp.css
  src/pages/Post.js
  src/pages/PostUpdate.js
Labels: bug, enhancement

#68 Feature/list
  src/components/Comment.jsx
  src/components/ListInComp.js
  src/css/ListInComp.css
  src/pages/ListIn.jsx
  src/pages/ParserTest.js
Labels: enhancement
